### ISSUE TITLE
Hi, can this project be deployed on Windows?

### ISSUE THREAD

**Issue by ptf010** [npolizzi/Combs#21]
Hello Nicholas,
      can this project be deployed on Windows?
   thanks,
ptf010

**Comment by npolizzi** [comment]
Hi, I would recommend using the published version of Combs2, which can be found in Version V2 of this Zenodo deposit: https://doi.org/https://doi.org/10.5281/zenodo.10653015.  The code is written for linux and mac. You would need to install a linux partition on your Windows machine to use it, I would think.

**Comment by ptf010** [comment]
Got it. Thanks a lot.       
Hey there! Could you possibly tell me the difference between param_gly and param_ala files? Or how I should get them？ Thanks so much!
ptf010

**Comment by npolizzi** [comment]
param_gly are parametric bundles with glycine residues, param_ala are parametric bundles with alanine residues

**Comment by ptf010** [comment]
Hello Does this programme require a GUI for the linux server?
I look forward to your reply.
Thanks so much!
ptf010

**Comment by ptf010** [comment]
Hello I'm getting this error. Can you help me see what's wrong?  Thank you very much.  

(env_combs) [tengfei416@mu01 biotin]$ python run_design.py
/home/tengfei416/miniconda3/envs/env_combs/lib/python3.8/site-packages/numba/np/ufunc/parallel.py:355: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 6103. The TBB threading layer is disabled.
  warnings.warn(problem)
Input directory: /home/tengfei416/combs/combs/tutorials/files/HPC_scripts/biotin/
Output directory: /home/tengfei416/combs/combs/tutorials/files/HPC_scripts/biotin/output/
@> 850 atoms and 1 coordinate set(s) were parsed in 0.01s.
@> 1213 atoms and 1 coordinate set(s) were parsed in 0.01s.
Traceback (most recent call last):
  File "run_design.py", line 287, in <module>
    main()
  File "run_design.py", line 44, in main
    template.set_alpha_hull(pdb_ala, alpha=9)
  File "/home/tengfei416/combs/combs/combs2/design/template.py", line 228, in set_alpha_hull
    self.alpha_hull.set_coords(pdb_w_CB)
  File "/home/tengfei416/combs/combs/combs2/design/convex_hull.py", line 116, in set_coords
    self._set_coords(pdb)
  File "/home/tengfei416/combs/combs/combs2/design/convex_hull.py", line 124, in _set_coords
    self.coords = pdb.select('name CB or (resname GLY and name CA)').getCoords()
  File "/home/tengfei416/miniconda3/envs/env_combs/lib/python3.8/site-packages/prody/atomic/atomic.py", line 234, in select
    return SELECT.select(self, selstr, **kwargs)
  File "/home/tengfei416/miniconda3/envs/env_combs/lib/python3.8/site-packages/prody/atomic/select.py", line 891, in select
    indices = self.getIndices(atoms, selstr, **kwargs)
  File "/home/tengfei416/miniconda3/envs/env_combs/lib/python3.8/site-packages/prody/atomic/select.py", line 949, in getIndices
    torf = self.getBoolArray(atoms, selstr, **kwargs)
  File "/home/tengfei416/miniconda3/envs/env_combs/lib/python3.8/site-packages/prody/atomic/select.py", line 1000, in getBoolArray
    parser = self._getParser(selstr)
  File "/home/tengfei416/miniconda3/envs/env_combs/lib/python3.8/site-packages/prody/atomic/select.py", line 1096, in _getParser
    parser = pp.operatorPrecedence(expr, oplist)
AttributeError: module 'pyparsing' has no attribute 'operatorPrecedence'
